# Generated by Django 5.0.2 on 2024-03-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='packaging_size',
            field=models.CharField(choices=[('100mg', '100mg'), ('200mg', '200mg'), ('300mg', '300mg'), ('400mg', '400mg'), ('500mg', '500mg'), ('30 capsules', '30 capsules'), ('60 capsules', '60 capsules'), ('90 capsules', '90 capsules')], default='100mg', max_length=100),
        ),
    ]
