# Generated by Django 5.0.2 on 2024-08-04 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_order_created_orderitem_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='drugID',
            new_name='drug',
        ),
    ]
