# Generated by Django 5.0.2 on 2024-03-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_drug_packaging_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='stock_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
