# Generated by Django 5.0.2 on 2024-08-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_order_options_rename_drugid_orderitem_drug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='orderID',
            new_name='order',
        ),
    ]
