# Generated by Django 5.0.2 on 2024-03-31 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_drug_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='strength',
        ),
    ]
