# Generated by Django 5.0.2 on 2024-08-04 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_orderid_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='drugs',
        ),
    ]
