# Generated by Django 5.0.2 on 2024-03-31 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_drug_dosage_remove_drug_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_per_item',
        ),
    ]
