# Generated by Django 5.0.2 on 2024-04-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
