# Generated by Django 5.0.2 on 2024-04-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_order_order_date_remove_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='items', to='backend.order'),
        ),
    ]
